// Copies the escrow ABI out of the Foundry build into a typed TS module, so the app never reads
// contracts/out at runtime and `as const` gives viem full type inference. Run after `forge build`.
import { readFileSync, writeFileSync } from 'node:fs'

const artifact = JSON.parse(readFileSync(new URL('../contracts/out/KashLinkEscrow.sol/KashLinkEscrow.json', import.meta.url), 'utf8'))
const out = new URL('../src/lib/escrow-abi.ts', import.meta.url)

writeFileSync(out, `// Generated by \`npm run abi\` from contracts/out — do not edit.\nexport const ESCROW_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const\n`)
console.log(`wrote ${out.pathname} (${artifact.abi.length} entries)`)
